name = "ProfileVega"
uuid = "4391764f-db79-4bd7-a4c6-f9062de4300e"
authors = ["David Anthoff <anthoff@berkeley.edu>"]
version = "1.1.2-DEV"

[deps]
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
LeftChildRightSiblingTrees = "1d6d02ad-be62-4b6b-8a6d-2f90e265016e"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
FlameGraphs = "0.1, 0.2, 1"
LeftChildRightSiblingTrees = "0.1.1"
VegaLite = "1, 2.0"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
